before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: j8m3GsHD4TrQ9Afid273VUQ2RId+2+KhqguwilzmBMBtkDEF6oSO+dYGpIeTG+Qd5keX0ldqAxnyPusZ87nmtUZCJ3ebi8HDZuMNn3hoQW+fM1fve6V+16QnGSFHYUmcH+EtOZajN+H2b9AEYMLzbbe1TQD/QJa3wYfH2I6UK+h3h7Sq7hhoSxA0wXK4NkS/zK2Q9gLtlhgUyZ4Py1GaEXX39kiI+t8sKh7JIUJUutHhGfjuS4jMkyLfDw18+gH42NCS+JN/z/lZe8R218DU9EWu5GlX4W16nTolvEfjuCSFeIE3W3U9UWR1omlwiZucuDyYKBWCGXmn8fHx3u7K/IPw3vrcznC/t7uLc8KFE2naWqRqoPRNsY3xSWc8j4sX6MtdepVdDGKwhWJ8Roy2XxOvN6ljgb5zIswyKOYhm+WK/RYyagdIDUrh1omJQKkPvAdL4azDVBz9JKSMAsmHnPFsfbVxO/P3sIJSAwTp6BhEuOj6A2u00afk3zkQTupHt4ZOc1Z0S+W87WDjIM1gIeTkmlODRzfVHhXWnwYxTL+hLYjZkIGCukF2zf2ySgU2KLMgC/Z09g0ldPN2OM/9HAg/pM1KJPKgDhwysDhBPzjSfhM8JHLtAJAlTN9QQtEuzSogFx+HnxcQ+AevN9nHDzhOmFQYZFzxBuEsF67eatY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
